### ISSUE TITLE
CUDAapi.jl is deprecated

### ISSUE THREAD

**Issue by jaepillee0315** [QuantEcon/quantecon-notebooks-julia#8]
For an unconscientious user, 
```
using InstantiateFromURL
github_project("QuantEcon/quantecon-notebooks-julia", version = "0.8.0", instantiate = true, precompile = true)
```
installs `CUDAapi.jl`, which clashes with recent versions of `CUDA.jl` and its family, it seems.

**Comment by jlperla** [comment]
Thanks. I think many of these package versions are due for a bump, and I suspect this is one of the subdependencies. That said, the package versions are really intended to support the concurrent usage of all of the lectures, and you are better off creating your own package/manifest for your own projectsv(with as few dependencies as possible!) in all cases

**Comment by jaepillee0315** [comment]
Thanks for your tip! I naively used quantecon's project/manifest because I don't have a clear idea how it is used. This is the time now for me to spend some time to understand them.
