### ISSUE TITLE
Relationship to lecture-julia.notebooks

### ISSUE THREAD

**Issue by nicolas-jimenez** [QuantEcon/quantecon-notebooks-julia#9]
What is the relationship between this repository and [QuantEcon/lecture-julia.notebooks](https://github.com/QuantEcon/lecture-julia.notebooks)? Is this repository deprecated? Thanks!

**Comment by jlperla** [comment]
@nicolas-jimenez  This repository is being deprecated, as it was generated by the older build system.  We will leave it up for another month or two before we completely remove the old infraastructure.

Thanks!
